// Code generated by mockery v1.0.0. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockInitializer is an autogenerated mock type for the Initializer type
type MockInitializer struct {
	mock.Mock
}

// Metric provides a mock function with given fields: _a0
func (_m *MockInitializer) Metric(_a0 *Metric) {
	_m.Called(_a0)
}
